### PR TITLE
:sparkles: Complete serializer

### LINKED ISSUE #76: Cannot serialize sequence of tags
I was using `serde-xml-rs` with the [`vkxml`](https://github.com/terrybrashaw/vkxml) crate in one of my projects, and although the structures it exposes implement `Serialize`, the serialization fails due to `serialize_seq()` not being supported in `serde-xml-rs`, as described in [this code block](https://github.com/RReverser/serde-xml-rs/blob/551c78d155cac89815e28d0f36a87029a8bf2a62/src/ser/mod.rs#L236-L241).

In this library, a valid `vk_new.xml` file is represented an ordered sequence of `RegistryElement` tags (see the [lib.rs](https://github.com/terrybrashaw/vkxml/blob/master/src/lib.rs#L8)). Therefore, it intuitively appears straightforward to iterate over each element in the sequence and serialize them in turn. However, the comment left in the `serialize_seq()` method leads me to believe that this task isn't as simple as it seems.

Would anyone please elaborate on why this behavior isn't supported?

**EDIT:** I see that https://github.com/RReverser/serde-xml-rs/pull/36 has been open for about a year. What's the status?

### LINKED ISSUE #138: Serialise/Deserialise functions should sanitze xml special characters
some characters in tags/values do not seem to be sanitized - for instance `&` should be replaced with `&amp;`

the `xml-rs` package can do this satitization.

### LINKED ISSUE #140: Clarify how attributes are handled
In the Github readme you have this example:

```
struct Item {
    pub name: String,
    pub source: String
}
// <Item name="hello" source="world.rs" />
```

And in the documentation you have:

```
struct Item {
    name: String,
    source: String,
}
// <Item><name>Banana</name><source>Store</source></Item>
```

It's not immediately obvious how the different styles are handled. E.g. what happens if you have this:

    <Item name="Orange"><name>Banana</name>...

If I do 

```
struct Item {
    name: String,
    source: Vec<String>,
}
```

Will it still decode this:

    <Item source="Orange">...

Or only this:

    <Item><source>Store</source><source>Jungle</source>...

It would be good to document it.

### PR DESCRIPTION
**Pull request by punkstarman**
Fixes #76, fixes #138, fixes #140

### CODE REVIEW

**Comment by elpiel** [comment]
I must check this one out!
Thanks!

**Comment by christopher-drews** [comment]
@punkstarman, is a release planned after this merge?

**Comment by punkstarman** [comment]
@christopher-drews, thanks for your interest.

I will try to release a new version this weekend at the latest. If you don't hear from me by then, don't hesitate to remind me Monday.

**Comment by paulvt** [comment]
@punkstarman This is the requested reminder 😉

**Comment by samanpa** [comment]
@punkstarman Any chance we might get a release soon.

**Comment by punkstarman** [comment]
Yeah sorry @paulvt , @KatsuoRyuu , @samanpa . Thanks for the reminders. I'll get to it today.

**Comment by elpiel** [comment]
@punkstarman that's great! Have you been able to work on the deserializatoin part? More specifically the attributes that we've talked about before?

**Comment by punkstarman** [comment]
@elpiel, I would like to work on it soon.

**Pull request merged**
