### PR TITLE
Improve Bool parsing and add sequence serialization

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by oli-obk** [comment]
Sorry, we won't support this. Use `serde(deserialize_with)` instead. Reasoning: https://github.com/RReverser/serde-xml-rs/pull/18#issuecomment-309452068

**Comment by farodin91** [comment]
Also dublicated sequence serialization see #36

**Comment by MarcAntoine-Arnaud** [comment]
Regarding Boolean, the [W3C standard](https://www.w3.org/TR/xmlschema-2/#boolean) mention `·boolean· can have the following legal literals {true, false, 1, 0}`.
This is why it can made sense to add it in this library.

**Comment by oli-obk** [comment]
@RReverser opinions?

**Comment by RReverser** [comment]
>   3.2.2.1 Lexical representation
  An instance of a datatype that is defined as ·boolean· can have the 
  following legal literals {true, false, 1, 0}. 

>  3.2.2.2 Canonical representation
  The canonical representation for boolean is the set of 
  literals {true, false}. 

This is interesting indeed. If that's called a canonical representation by spec, I agree it's a game changer and makes sense to support it by default (assuming we are still able to have helper functions for `0` / `1` and "exists" / "doesn't exist" representations).

**Comment by RReverser** [comment]
@MarcAntoine-Arnaud Could you please split your commits into two PRs so that we don't mix discussions?

**Pull request closed without merging**
