### PR TITLE
Prevent infinite loop at the end of the document

### LINKED ISSUE #3: Infinite Loop when parsing Vec
This results in an infinite loop:
```rust
let tickets: Vec<Ticket> = deserialize(xml.as_bytes()).unwrap();
```
When used on a xml doc that has multiple root elements.

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #3 

@oli-obk r?

### CODE REVIEW

**Comment by oli-obk** [comment]
lgtm, thanks

**Comment by Boscop** [comment]
Thanks!
So now it also works with multiple root elements?

**Comment by oli-obk** [comment]
No. It errors nicely ;)

**Comment by oli-obk** [comment]
Ah no I misread the PR. It works... hmm... that was unintended in the issue, but I like it nontheless... We should probably make something like that explicit. I'll open an issue to discuss.

**Pull request merged**
