### PR TITLE
Run rustfmt

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by RReverser** [comment]
It would be nice if this was part of serializer PR... Anyway, are you using rustfmt-nightly? (to make sure we use the same tool)

**Comment by oli-obk** [comment]
> Anyway, are you using rustfmt-nightly? (to make sure we use the same tool)

Nope, I'm running simply `rustfmt`.

**Comment by RReverser** [comment]
Could you please run the new one? It's the one in most active development anyway, and it has much better defaults for formatting.

**Comment by oli-obk** [comment]
sure

**Comment by oli-obk** [comment]
You're right, this is much better

**Comment by oli-obk** [comment]
don't merge until #20 is through. Running rustfmt is much easier than rebasing around a rustfmt change.

**Comment by RReverser** [comment]
@oli-obk I see it's merged, just curious - what's the difference? (especially for PR with one commit)

Rebasing on top of autoformatted code is usually as easy as autoformatting your own PR and then rebasing, most conflicts go away on their own.

**Comment by oli-obk** [comment]
> Rebasing on top of autoformatted code is usually as easy as autoformatting your own PR and then rebasing, most conflicts go away on their own.

True... I just have had some bad experience with it.

**Pull request merged**
