### PR TITLE
Update to serde 1.0.0 and xml-rs 0.4.1

### PR DESCRIPTION
**Pull request by farodin91**

### CODE REVIEW

**Comment by RReverser** [comment]
Thanks for the PR! But this is huge and seems to change many things not directly related to the upgrade. Could you please update it to leave them as-is?

**Comment by SamWhited** [comment]
Looks like `rustfmt` got run; might be worth requiring that in future for consistencies sake; but that's a separate issue.

**Comment by farodin91** [comment]
I reduced changes

**Comment by oli-obk** [comment]
@farodin91 there's still a lot of noise. Could you do a separate commit for the rustfmt changes and rebase your other commit over those? After the rebase all the rustfmt changes in the second commit should be gone, and then we only need to look at the second commit. This should save you a lot of work (since you don't have to undo any changes, but can let rustfmt and git do the work for you).

**Pull request closed without merging**
