### PR TITLE
Some Normalization and switch to error_chain

### PR DESCRIPTION
**Pull request by farodin91**
Running rustfmt

### CODE REVIEW

**Comment by RReverser** [comment]
Frankly calls look much less readable after rustfmt to me. Wish [`prettier`](http://jlongster.com/A-Prettier-Formatter) would work for Rust...

**Comment by farodin91** [comment]
I can change them block calls. https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#fn_args_layout

**Comment by RReverser** [comment]
I really liked the new defaults in rustfmt-nightly (http://www.ncameron.org/blog/rustfmt-changes/), solves most of concerns I had with rustfmt defaults, so I went ahead and formatted codebase with it.

**Comment by farodin91** [comment]
I could rebase my changes to current version.

**Pull request closed without merging**
