### PR TITLE
feature: update dependency: log 0.3.6 -> log 0.4

### PR DESCRIPTION
**Pull request by Dushistov**
Dependency from log 0.3.6 cause dependency duplication in any crate that depend on serde-xml-rs, because of almost all other crate already migrate to log 0.4.x.

### CODE REVIEW

**Comment by Dushistov** [comment]
> I'm not convinced of the means used though, for two reasons.

You missed two things:

1. For all `.rs` files inside `crate/tests` `cargo` build binary.
   For example for
```sh
$ cat tests/test_foo.rs
mod boo;
$ cat boo.rs
$
```
  `cargo test` builds two binaries one from test_foo.rs + boo.rs and other from `boo.rs`
  you can see it via `cargo test -vv`
2. It is impossible to refer code marked via `#[cfg(test)]` from other crate.

So all other options create overhead: public api in serde-xml-rs (because of 2) or one more executable that cargo build and run

> Any thoughts on the tradeoff between reinventing the wheel and adding a test dependency?

env_logger produce output only if env variables set, but there is https://crates.io/crates/simple_logger ,
and with `dev-dependency` it should not hurt anyone.

**Comment by punkstarman** [comment]
> > I'm not convinced of the means used though, for two reasons.
> 
> You missed two things:
> 
> 1. For all `.rs` files inside `crate/tests` `cargo` build binary.
>    For example for
> 
> ```shell
> $ cat tests/test_foo.rs
> mod boo;
> $ cat boo.rs
> $
> ```
> 
> `cargo test` builds two binaries one from test_foo.rs + boo.rs and other from `boo.rs`
> you can see it via `cargo test -vv`

See the [relevant section in the Rust Book](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests) for how to put a shared module for integration tests without Cargo building a crate for it.

> 2. It is impossible to refer code marked via `#[cfg(test)]` from other crate.

Quite true, which makes me lean even more towards putting this shared init code in the `tests` directory.

> 
> > Any thoughts on the tradeoff between reinventing the wheel and adding a test dependency?
> 
> env_logger produce output only if env variables set, but there is https://crates.io/crates/simple_logger ,
> and with `dev-dependency` it should not hurt anyone.

I agree. Feel free to refactor `init_logger` to use `simple_logger` if you can. IMO, this isn't required but would be nice.

**Comment by Dushistov** [comment]
>I agree. Feel free to refactor init_logger to use simple_logger if you can. IMO, this isn't required but would 
>be nice.

I remove `init_logger` completely, `simple_logger` show `debug!` by default, so there is no need for any configuration.

**Comment by punkstarman** [comment]
I kind of liked the `init_logger` abstraction, but OK. We can have this debate another time.

**Pull request merged**
